/* Generated by tools/build-manual.py -- edit that, not this.

   Opens a figure at its captured size when it is clicked, and closes on Escape.

   Why it exists: the manual's figures can be drawn smaller than they were captured, and the text in a
   settings window goes soft when it is. Widening the page would ruin the measure for reading, so a
   reader gets 1:1 on demand instead.

   Three things it deliberately does NOT do:
     - it never touches the address bar. No hash and no history entry, so Back still leaves the page
       rather than closing a dialog;
     - it adds no dependency. This is the only script on the site;
     - it is not injected into docs/help, so the .chm - whose viewer is an old IE engine that would
       make nothing of this - never sees it.
*/
(function () {
  "use strict";

  var box, picture, caption, opener;

  function build() {
    box = document.createElement("div");
    box.id = "shotbox";
    box.setAttribute("role", "dialog");
    box.setAttribute("aria-modal", "true");
    box.setAttribute("aria-label", "Screenshot at full size");

    var close = document.createElement("button");
    close.type = "button";
    close.textContent = "Close (Esc)";

    picture = document.createElement("img");
    caption = document.createElement("figcaption");

    var hint = document.createElement("p");
    hint.className = "hint";
    hint.textContent = "Press Escape, or click anywhere outside the image.";

    box.appendChild(close);
    box.appendChild(picture);
    box.appendChild(caption);
    box.appendChild(hint);
    document.body.appendChild(box);

    // Clicking the backdrop closes; clicking the image itself does not, so a large shot can be
    // scrolled without it vanishing from under the reader.
    box.addEventListener("click", function (event) {
      if (event.target !== picture) {
        hide();
      }
    });
  }

  function show(image) {
    if (!box) {
      build();
    }

    opener = image;
    picture.src = image.currentSrc || image.src;
    picture.alt = image.alt || "";

    // naturalWidth is the captured size, which is the number the reader came for. It goes in the
    // caption as well, so it is evident this is 1:1 rather than another arbitrary scale.
    var size = image.naturalWidth
      ? image.naturalWidth + " x " + image.naturalHeight + " pixels"
      : "";

    caption.textContent = (image.alt ? image.alt + " - " : "") + size;

    box.classList.add("open");
    document.body.classList.add("shotbox-open");
    box.scrollTop = 0;
    box.querySelector("button").focus();
  }

  function hide() {
    if (!box || !box.classList.contains("open")) {
      return;
    }

    box.classList.remove("open");
    document.body.classList.remove("shotbox-open");

    // Focus goes back where it came from, or a keyboard reader is dropped at the top of the document.
    if (opener && opener.focus) {
      opener.focus();
    }
  }

  /* Which images open.

     Not a list of container classes: that is how PasteJump's first version missed every image on its
     landing page. The test is the reason a reader wants this at all - the image is being DRAWN SMALLER
     THAN IT WAS CAPTURED, and it is content rather than decoration. An image with no alt text is
     decoration by definition - the sidebar's brand icon is alt="" - and the brand is excluded by name
     besides. The 1px rule is there because a browser can report a fractional width for an image at its
     natural size. */
  function openable(image) {
    if (image.tagName !== "IMG" || !image.alt) {
      return false;
    }

    if (image.closest(".brand")) {
      return false;
    }

    // The landing page's tour is a <video> whose <img> is a fallback for a browser that cannot play
    // it. Where the video plays, that image is never drawn - clientWidth 0 - so the arithmetic below
    // would mark an invisible image openable. The video is not a figure and is left alone.
    if (image.closest("video")) {
      return false;
    }

    // A figure in the manual always opens, even where the column happens to fit it: those are windows
    // and panels, and a reader who clicks one wants its pixels whatever the arithmetic says.
    if (image.closest("p.figure")) {
      return true;
    }

    return image.naturalWidth > image.clientWidth + 1;
  }

  document.addEventListener("click", function (event) {
    if (!openable(event.target)) {
      return;
    }

    event.preventDefault();
    show(event.target);
  });

  document.addEventListener("keydown", function (event) {
    if (event.key === "Escape") {
      hide();
    }
  });

  /* Reachable without a mouse: every openable figure becomes focusable and answers Enter and Space.

     On "load", NOT "DOMContentLoaded": openable() asks for naturalWidth and clientWidth, and at
     DOMContentLoaded the images have not been fetched or laid out, so both are 0 and nothing outside a
     figure would be marked. The click handler is unaffected either way, since it evaluates when the
     click happens. */
  window.addEventListener("load", function () {
    var shots = document.querySelectorAll("img");

    Array.prototype.forEach.call(shots, function (image) {
      if (!openable(image)) {
        return;
      }

      // zoom-in is set here as well as in the stylesheet, because whether an image outside a figure
      // is openable depends on how big it ended up being drawn, which CSS cannot ask about.
      image.style.cursor = "zoom-in";
      image.tabIndex = 0;

      if (!image.title) {
        image.title = "Click to see it at full size";
      }

      image.addEventListener("keydown", function (event) {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          show(image);
        }
      });
    });
  });
})();
